const countries = [
 { country_name: 'Afghanistan', iso: 'AF' },
 { country_name: 'Albania', iso: 'AL' },
 { country_name: 'Algeria', iso: 'DZ' },
 { country_name: 'American Samoa', iso: 'AS' },
 { country_name: 'Andorra', iso: 'AD' },
 { country_name: 'Angola', iso: 'AO' },
 { country_name: 'Anguilla', iso: 'AI' },
 {
   country_name: 'Antigua and Barbuda',
   iso: 'AG'
 },
 { country_name: 'Argentina', iso: 'AR' },
 { country_name: 'Armenia', iso: 'AM' },
 { country_name: 'Aruba', iso: 'AW' },
 { country_name: 'Australia', iso: 'AU' },
 { country_name: 'Austria', iso: 'AT' },
 { country_name: 'Azerbaijan', iso: 'AZ' },
 { country_name: 'Bahrain', iso: 'BH' },
 { country_name: 'Bangladesh', iso: 'BD' },
 { country_name: 'Barbados', iso: 'BB' },
 { country_name: 'Belarus', iso: 'BY' },
 { country_name: 'Belgium', iso: 'BE' },
 { country_name: 'Belize', iso: 'BZ' },
 { country_name: 'Benin', iso: 'BJ' },
 { country_name: 'Bermuda', iso: 'BM' },
 { country_name: 'Bhutan', iso: 'BT' },
 { country_name: 'Bolivia', iso: 'BO' },
 {
   country_name: 'Bosnia and Herzegovina',
   iso: 'BA'
 },
 { country_name: 'Botswana', iso: 'BW' },
 { country_name: 'Brazil', iso: 'BR' },
 {
   country_name: 'British Virgin Islands',
   iso: 'VG'
 },
 { country_name: 'Brunei', iso: 'BN' },
 { country_name: 'Bulgaria', iso: 'BG' },
 { country_name: 'Burkina Faso', iso: 'BF' },
 { country_name: 'Burundi', iso: 'BI' },
 { country_name: 'Cabo Verde', iso: 'CV' },
 { country_name: 'Cambodia', iso: 'KH' },
 { country_name: 'Cameroon', iso: 'CM' },
 { country_name: 'Canada', iso: 'CA' },
 { country_name: 'Cayman Islands', iso: 'KY' },
 {
   country_name: 'Central African Republic',
   iso: 'CF'
 },
 { country_name: 'Chad', iso: 'TD' },
 { country_name: 'Chile', iso: 'CL' },
 { country_name: 'China', iso: 'CN' },
 { country_name: 'Colombia', iso: 'CO' },
 { country_name: 'Comoros', iso: 'KM' },
 { country_name: 'Congo', iso: 'CG' },
 {
   country_name: 'Congo Democratic Republic',
   iso: 'CD'
 },
 { country_name: 'Cook Islands', iso: 'CK' },
 { country_name: 'Costa Rica', iso: 'CR' },
 { country_name: "Cote d'Ivoire", iso: 'CI' },
 { country_name: 'Croatia', iso: 'HR' },
 { country_name: 'Cuba', iso: 'CU' },
 { country_name: 'Curaçao', iso: 'CW' },
 { country_name: 'Cyprus', iso: 'CY' },
 { country_name: 'Czechia', iso: 'CZ' },
 { country_name: 'Denmark', iso: 'DK' },
 { country_name: 'Djibouti', iso: 'DJ' },
 { country_name: 'Dominica', iso: 'DM' },
 { country_name: 'Dominican Republic', iso: 'DO' },
 { country_name: 'East Timor', iso: 'TL' },
 { country_name: 'Ecuador', iso: 'EC' },
 { country_name: 'Egypt', iso: 'EG' },
 { country_name: 'El Salvador', iso: 'SV' },
 { country_name: 'Equatorial Guinea', iso: 'GQ' },
 { country_name: 'Eritrea', iso: 'ER' },
 { country_name: 'Estonia', iso: 'EE' },
 { country_name: 'Ethiopia', iso: 'ET' },
 { country_name: 'Falkland Islands', iso: 'FK' },
 { country_name: 'Faroe Islands', iso: 'FO' },
 { country_name: 'Fiji', iso: 'FJ' },
 { country_name: 'Finland', iso: 'FI' },
 { country_name: 'France', iso: 'FR' },
 { country_name: 'French Polynesia', iso: 'PF' },
 { country_name: 'Gabon', iso: 'GA' },
 { country_name: 'Gambia', iso: 'GM' },
 { country_name: 'Georgia', iso: 'GE' },
 { country_name: 'Germany', iso: 'DE' },
 { country_name: 'Ghana', iso: 'GH' },
 { country_name: 'Gibraltar', iso: 'GI' },
 { country_name: 'Greece', iso: 'GR' },
 { country_name: 'Greenland', iso: 'GL' },
 { country_name: 'Grenada', iso: 'GD' },
 { country_name: 'Guam', iso: 'GU' },
 { country_name: 'Guatemala', iso: 'GT' },
 { country_name: 'Guernsey', iso: 'GG' },
 { country_name: 'Guinea', iso: 'GN' },
 { country_name: 'Guinea-Bissau', iso: 'GW' },
 { country_name: 'Guyana', iso: 'GY' },
 { country_name: 'Haiti', iso: 'HT' },
 { country_name: 'Honduras', iso: 'HN' },
 { country_name: 'Hong Kong', iso: 'HK' },
 { country_name: 'Hungary', iso: 'HU' },
 { country_name: 'Iceland', iso: 'IS' },
 { country_name: 'India', iso: 'IN' },
 { country_name: 'Indonesia', iso: 'ID' },
 { country_name: 'Iran', iso: 'IR' },
 { country_name: 'Iraq', iso: 'IQ' },
 { country_name: 'Ireland', iso: 'IE' },
 { country_name: 'Isle of Man', iso: 'IM' },
 { country_name: 'Israel', iso: 'IL' },
 { country_name: 'Italy', iso: 'IT' },
 { country_name: 'Jamaica', iso: 'JM' },
 { country_name: 'Japan', iso: 'JP' },
 { country_name: 'Jersey', iso: 'JE' },
 { country_name: 'Jordan', iso: 'JO' },
 { country_name: 'Kazakhstan', iso: 'KZ' },
 { country_name: 'Kenya', iso: 'KE' },
 { country_name: 'Kiribati', iso: 'KI' },
 { country_name: 'Kosovo', iso: 'XK' },
 { country_name: 'Kuwait', iso: 'KW' },
 { country_name: 'Kyrgyzstan', iso: 'KG' },
 { country_name: 'Laos', iso: 'LA' },
 { country_name: 'Latvia', iso: 'LV' },
 { country_name: 'Lebanon', iso: 'LB' },
 { country_name: 'Lesotho', iso: 'LS' },
 { country_name: 'Liberia', iso: 'LR' },
 { country_name: 'Libya', iso: 'LY' },
 { country_name: 'Liechtenstein', iso: 'LI' },
 { country_name: 'Lithuania', iso: 'LT' },
 { country_name: 'Luxembourg', iso: 'LU' },
 { country_name: 'Macau', iso: 'MO' },
 { country_name: 'Madagascar', iso: 'MG' },
 { country_name: 'Malawi', iso: 'MW' },
 { country_name: 'Malaysia', iso: 'MY' },
 { country_name: 'Maldives', iso: 'MV' },
 { country_name: 'Mali', iso: 'ML' },
 { country_name: 'Malta', iso: 'MT' },
 { country_name: 'Marshall Islands', iso: 'MH' },
 { country_name: 'Martinique', iso: 'MQ' },
 { country_name: 'Mauritania', iso: 'MR' },
 { country_name: 'Mauritius', iso: 'MU' },
 { country_name: 'Mayotte', iso: 'YT' },
 { country_name: 'Mexico', iso: 'MX' },
 { country_name: 'Micronesia', iso: 'FM' },
 { country_name: 'Moldova', iso: 'MD' },
 { country_name: 'Monaco', iso: 'MC' },
 { country_name: 'Mongolia', iso: 'MN' },
 { country_name: 'Montenegro', iso: 'ME' },
 { country_name: 'Montserrat', iso: 'MS' },
 { country_name: 'Morocco', iso: 'MA' },
 { country_name: 'Mozambique', iso: 'MZ' },
 { country_name: 'Myanmar', iso: 'MM' },
 { country_name: 'Namibia', iso: 'NA' },
 { country_name: 'Nauru', iso: 'NR' },
 { country_name: 'Nepal', iso: 'NP' },
 { country_name: 'Netherlands', iso: 'NL' },
 { country_name: 'New Caledonia', iso: 'NC' },
 { country_name: 'New Zealand', iso: 'NZ' },
 { country_name: 'Nicaragua', iso: 'NI' },
 { country_name: 'Niger', iso: 'NE' },
 { country_name: 'Nigeria', iso: 'NG' },
 { country_name: 'North Korea', iso: 'KP' },
 { country_name: 'North Macedonia', iso: 'MK' },
 {
   country_name: 'Northern Mariana Islands',
   iso: 'MP'
 },
 { country_name: 'Norway', iso: 'NO' },
 { country_name: 'Oman', iso: 'OM' },
 { country_name: 'Pakistan', iso: 'PK' },
 { country_name: 'Palau', iso: 'PW' },
 { country_name: 'Panama', iso: 'PA' },
 { country_name: 'Papua New Guinea', iso: 'PG' },
 { country_name: 'Paraguay', iso: 'PY' },
 { country_name: 'Peru', iso: 'PE' },
 { country_name: 'Philippines', iso: 'PH' },
 { country_name: 'Poland', iso: 'PL' },
 { country_name: 'Portugal', iso: 'PT' },
 { country_name: 'Puerto Rico', iso: 'PR' },
 { country_name: 'Qatar', iso: 'QA' },
 { country_name: 'Reunion', iso: 'RE' },
 { country_name: 'Romania', iso: 'RO' },
 { country_name: 'Russia', iso: 'RU' },
 { country_name: 'Rwanda', iso: 'RW' },
 { country_name: 'Saint Helena', iso: 'SH' },
 {
   country_name: 'Saint Kitts and Nevis',
   iso: 'KN'
 },
 { country_name: 'Saint Lucia', iso: 'LC' },
 { country_name: 'Saint Martin', iso: 'MF' },
 {
   country_name: 'Saint Pierre and Miquelon',
   iso: 'PM'
 },
 {
   country_name: 'Saint Vincent and the Grenadines',
   iso: 'VC'
 },
 { country_name: 'Samoa', iso: 'WS' },
 { country_name: 'San Marino', iso: 'SM' },
 {
   country_name: 'Sao Tome and Principe',
   iso: 'ST'
 },
 { country_name: 'Saudi Arabia', iso: 'SA' },
 { country_name: 'Senegal', iso: 'SN' },
 { country_name: 'Serbia', iso: 'RS' },
 { country_name: 'Seychelles', iso: 'SC' },
 { country_name: 'Sierra Leone', iso: 'SL' },
 { country_name: 'Singapore', iso: 'SG' },
 { country_name: 'Sint Maarten', iso: 'SX' },
 { country_name: 'Slovakia', iso: 'SK' },
 { country_name: 'Slovenia', iso: 'SI' },
 { country_name: 'Solomon Islands', iso: 'SB' },
 { country_name: 'Somalia', iso: 'SO' },
 { country_name: 'South Africa', iso: 'ZA' },
 { country_name: 'South Korea', iso: 'KR' },
 { country_name: 'South Sudan', iso: 'SS' },
 { country_name: 'Spain', iso: 'ES' },
 { country_name: 'Sri Lanka', iso: 'LK' },
 { country_name: 'St. Barts', iso: 'BL' },
 { country_name: 'Sudan', iso: 'SD' },
 { country_name: 'Suriname', iso: 'SR' },
 { country_name: 'Sweden', iso: 'SE' },
 { country_name: 'Switzerland', iso: 'CH' },
 { country_name: 'Syria', iso: 'SY' },
 { country_name: 'Taiwan', iso: 'TW' },
 { country_name: 'Tajikistan', iso: 'TJ' },
 { country_name: 'Tanzania', iso: 'TZ' },
 { country_name: 'Thailand', iso: 'TH' },
 { country_name: 'The Bahamas', iso: 'BS' },
 { country_name: 'Togo', iso: 'TG' },
 { country_name: 'Tonga', iso: 'TO' },
 {
   country_name: 'Trinidad and Tobago',
   iso: 'TT'
 },
 { country_name: 'Tunisia', iso: 'TN' },
 { country_name: 'Turkey', iso: 'TR' },
 { country_name: 'Turkmenistan', iso: 'TM' },
 {
   country_name: 'Turks and Caicos Islands',
   iso: 'TC'
 },
 { country_name: 'Tuvalu', iso: 'TV' },
 { country_name: 'US Virgin Islands', iso: 'VI' },
 { country_name: 'Uganda', iso: 'UG' },
 { country_name: 'Ukraine', iso: 'UA' },
 {
   country_name: 'United Arab Emirates',
   iso: 'AE'
 },
 { country_name: 'United Kingdom', iso: 'GB' },
 { country_name: 'United States', iso: 'US' },
 { country_name: 'Uruguay', iso: 'UY' },
 { country_name: 'Uzbekistan', iso: 'UZ' },
 { country_name: 'Vanuatu', iso: 'VU' },
 {
   country_name: 'Vatican City (Holy See)',
   iso: 'VA'
 },
 { country_name: 'Venezuela', iso: 'VE' },
 { country_name: 'Vietnam', iso: 'VN' },
 { country_name: 'Wallis and Futuna', iso: 'WF' },
 { country_name: 'Yemen', iso: 'YE' },
 { country_name: 'Zambia', iso: 'ZM' },
 { country_name: 'Zimbabwe', iso: 'ZW' },
 { country_name: 'eSwatini', iso: 'SZ' }
]

module.exports = countries;